/* Service to fetch time series data from our system.
 *
 * Time series data is produced by the device and sent in the form of messages.
 * Messages are parsed to a number of values (depending on the parser), which can be retrieved using this service.
 */
syntax = "proto3";

package hiber.value;

import "base.proto";
import "modem.proto";
import "process_point.proto";
import "value.proto";

option java_multiple_files = false;
option java_package = "global.hiber.api.grpc.value";
option java_outer_classname = "ValueServiceApi";
option go_package = ".;hiber";

service ValueService {
    rpc List (ListValues.Request) returns (ListValues.Response) {
        /* When value owner is a process point. */
        option (permission_usage) = PROCESS_POINTS_VALUES;
        /* When value owner is a device. */
        option (permission_usage) = MODEM_VALUES;
        /* When value owner is a device. */
        option (support_permission_usage) = DEVICE_VIEW_ALL_LIFECYCLES;
    }

    rpc Downsampled (DownsampledValues.Request) returns (DownsampledValues.Response) {
        /* When value owner is a process point. */
        option (permission_usage) = PROCESS_POINTS_VALUES;
        /* When value owner is a device. */
        option (permission_usage) = MODEM_VALUES;
        /* When value owner is a device. */
        option (support_permission_usage) = DEVICE_VIEW_ALL_LIFECYCLES;
    }

    rpc Aggregated (AggregatedValues.Request) returns (AggregatedValues.Response) {
        /* When value owner is a process point. */
        option (permission_usage) = PROCESS_POINTS_VALUES;
        /* When value owner is a device. */
        option (permission_usage) = MODEM_VALUES;
        /* When value owner is a device. */
        option (support_permission_usage) = DEVICE_VIEW_ALL_LIFECYCLES;
    }

    rpc Latest (LatestValues.Request) returns (LatestValues.Response) {
        /* When value owner is a process point. */
        option (permission_usage) = PROCESS_POINTS_VALUES;
        /* When value owner is a device. */
        option (permission_usage) = MODEM_VALUES;
        /* When value owner is a device. */
        option (support_permission_usage) = DEVICE_VIEW_ALL_LIFECYCLES;
    }
}

/* Select the values to return. */
message ValueSelection {
    /* Select the data by numeric value type.
     * If the list is empty, all fields are returned.
     */
    message ByField {
        repeated string fields = 1;
    }

    /* Select the data by (numeric) value type.
     * If the selection is empty, all values with all types are returned.
     */
    message ByValueType {
        repeated Value.Type value_type = 2;
        repeated Value.Numeric.Type numeric_value_type = 1;
    }

    /* Select the owners (either process points or devices) to get the values for. */
    oneof owner_selection {
        /* Select the devices(s) to get the values for. */
        modem.ModemSelection devices = 1;

        /* Select the process   point(s) to get the values for. */
        processpoint.ProcessPointSelection process_points = 11;
    }

    /* Select the type of values (either by field or by numeric value type) to get.
     * If no option is picked, ByField is assumed.
     */
    oneof data_selection {
        /* Get the values that are of the given numeric value types. */
        ByValueType value_type = 8;

        /* Get the values for the selected fields. */
        ByField field = 9;
    }

    /* Get the values for the selected fields. */
    repeated string fields = 2 [deprecated = true];

    /* The time to view the values for. */
    optional TimeRange time_range = 3;

    /* Include the location (which is not a field). */
    optional bool include_location = 4;

    /* Filter the values for enum fields. */
    repeated Filter.FieldEnumValues filter_enum_values = 6;

    /* Whether to include values that have been marked as operational (e.g. device status).
     * Operational data is typically only available when selecting values for a device.
     */
    optional bool include_operational_data = 10;
}

/* A Value at a time, for a given modem and field. */
message ValueContext {
    /* The device that produced this value. */
    ValueDeviceContext device = 8;

    /* The device that produced this value. */
    string device_number = 1 [deprecated = true];

    /* The process point that owns this value, if any.
     * Process points own this value if they were assigned to the device that produced this value at the time
     * it was produced.
     * If multiple process points were assigned at the same time, this value exists for each process point.
     */
    ValueProcessPointContext process_point = 9;

    /* The field that this value was produced for. */
    string field = 2;

    /* The time for this value. */
    Timestamp time = 3;

    oneof value_type {
        /* The value at this time, if no ValueTransformation was specified for this field. */
        Value value = 4;

        /* The output of the DURATION ValueTransformation, if it was specified for this field. */
        ValueDurations value_durations = 5;

        /* The output of the DELTA ValueTransformation, if it was specified for this field. */
        ValueDelta delta = 6;
    }

    /* Information about the process point that owns the value. */
    message ValueProcessPointContext {
        string identifier = 1;
        string name = 2;
        processpoint.ProcessPoint.Type type = 3;
    }

    /* The device data for this value. */
    message ValueDeviceContext {
        string number = 1;
        string identifier = 2;
        string name = 3;
    }

    /* The amount of time a field for a modem was at different values. */
    message ValueDurations {
        repeated ValueDuration durations = 1;
    }

    /* The amount of time a field for a modem was in this value. */
    message ValueDuration {
        /* The value the duration is for. */
        Value value = 1;

        /* The aggregated duration the field was this value. */
        Duration duration = 2;
    }

    /* The delta of a value: the difference between a value and the previous value. */
    message ValueDelta {
        /* The delta of the two values. */
        Value delta = 1;

        /* The value at this time. */
        Value current = 2;

        /* The previous value to compare it with. */
        Value previous = 3;
    }
}

/* List values for a (set of) modem(s), filtering by field and time. */
message ListValues {
    /* How to sort the values. */
    enum Sort {
        TIME_ASCENDING = 0;
        TIME_DESCENDING = 1;
    }

    message Request {
        /* Pick the organization to use (/impersonate). If unset, your default organization is used. */
        optional string organization = 1;
        ValueSelection selection = 2;
        optional Pagination pagination = 3;
        Sort sort = 4;

        /* Transform the values for a field into a derived value.
         * Fields specified here must have been specified in the selection.
         */
        map<string, ValueTransformation> transform_fields = 5;
    }

    message Response {
        repeated ValueContext values = 1;
        Pagination.Result pagination = 2;
        Request request = 3;
    }
}

/* Downsampled values for a (set of) modem(s), filtering by field and time. */
message DownsampledValues {
    /* Request downsampled values, reducing the selected time range to a single value per field. */
    message Request {
        /* Pick the organization to use (/impersonate). If unset, your default organization is used. */
        optional string organization = 1;

        /* The values to downsample.
         * When multiple modems are given, the data is downsampled separately and merged together in the response,
         * sorted by time.
         */
        ValueSelection selection = 2;

        /* Downsample the values to the given amount of data points. */
        optional uint32 points = 3;

        /* Paginate the downsampled values, if needed. */
        optional Pagination pagination = 4;

        /* How to sort the downsampled values. */
        ListValues.Sort sort = 5;

        /* Determine the lowest and highest values for each owner (device / process point). */
        optional bool determine_minimum_and_maximum_values = 6;
    }

    message Response {
        /* The downsampled values, mixed together and sorted by time (see sort in request). */
        repeated ValueContext downsampled_values = 1;

        Pagination.Result pagination = 2;
        Request request = 3;

        /* The lowest value for each owner (device / process point). */
        repeated ValueContext lowest = 4;

        /* The highest value for each owner (device / process point). */
        repeated ValueContext highest = 5;
    }
}

message AggregatedValues {
    /* The result of the aggregation. */
    oneof result {
        /* The value resulting from the aggregation. */
        Value value = 1;

        /* The count resulting from a COUNT or COUNT_DISTINCT aggregation. */
        Aggregation.CountResult count = 7;
    }

    /* The aggregation applied to get this value. */
    Aggregation aggregation = 2;

    /* The windowing configuration used for this value. */
    optional TimeWindow window = 3;

    /* The actual time range used for this aggregated value (e.g. window when windowing). */
    optional TimeRange time_range = 4;

    /* If the selected values all belonged to a single device, or group_by_owner was set, the device. */
    optional ValueContext.ValueDeviceContext device = 5;

    /* If the selected values all belonged to a single process point, or group_by_owner was set, the process point. */
    optional ValueContext.ValueProcessPointContext process_point = 6;

    /* Aggregation operation, e.g. min, max, count, sum or percentiles. */
    message Aggregation {
        /* Basic aggregation options, e.g. average, min, max, etc.
         * Options to be added in the future: MEDIAN, STANDARD_DEVIATION, etc
         */
        enum BasicAggregation {
            /* Counts the total number of selected values. */
            COUNT = 0;

            /* Counts the total number of UNIQUE values in the selected values. */
            COUNT_DISTINCT = 1;

            /* Calculates the total sum of all values in the selection. */
            SUM = 2;

            /* Calculates the mathematical average of the selected values. Alias for MEAN. */
            AVERAGE = 3;

            /* Calculates the mathematical mean of the selected values. Alias for AVERAGE. */
            MEAN = 4;

            /* Finds the lowest value of the selected values. */
            MINIMUM = 5;

            /* Finds the highest value of the selected values. */
            MAXIMUM = 6;

            /* Finds the most frequently occurring value of the selected values. */
            MODE = 7;

            /* Calculates the standard mathematical median (50th percentile). Uses continuous interpolation.
             * If there is an even number of rows, it will return the average of the two middle values.
             */
            MEDIAN = 8;

            /* Calculates the discrete median (50th percentile). Unlike the standard median this will never interpolate.
             * It guarantees returning an actual, existing value from the dataset
             * (picking the lower of the middle values if even).
             */
            MEDIAN_DISCRETE = 9;

            /* Calculates the Sample Standard Deviation.
             * Standard Deviation measures how spread out your data is from the Mean (average).
             * A *low* standard deviation means the data is tightly clustered around the average (highly predictable).
             * A *high* standard deviation means the data is widely spread out (highly volatile).
             * Use this for sensor readings, like pressure, which are a sample of real pressures.
             */
            STANDARD_DEVIATION = 10;

            /* Calculates the Population Standard Deviation. See STANDARD_DEVIATION.
             * Use this ONLY when your data represents the entire population (all possible values).
             */
            STANDARD_DEVIATION_POPULATION = 11;
        }

        /* Configurable percentile aggregation option. */
        message PercentileAggregation {
            /* The percentile to aggregate to, e.g. 75th, 90th, 99th, 99.999th.
             * (really any number, e.g. 88.12345 since it is a double)
             * Values between 0 and 1 are interpreted as using a range of 0 to 1, e.g. 0.995 -> 99.5th percentile.
             * Values higher than 100.0 or below 0 are not supported.
             */
            double percentile = 1;

            /* The method of calculation used for the percentile value: continuous or discrete. */
            PercentileAggregationMethod method = 2;

            /* The method of calculation used for the percentile value: continuous or discrete. */
            enum PercentileAggregationMethod {
                /* Always return an existing value from the selected values. Do not interpolate. */
                DISCRETE = 0;
                /* Interpolate between adjacent values if the target percentile falls between them. */
                CONTINUOUS = 1;
            }
        }

        /* Aggregation operation, e.g. min, max, count, sum or percentiles. */
        oneof aggregation {
            /* Basic aggregation options, e.g. average, min, max, etc. */
            BasicAggregation basic = 1;

            /* Configurable percentile aggregation option. */
            PercentileAggregation percentile = 2;
        }

        /* Counting does not return a value, just an integer, but we do want to know what we counted. */
        message CountResult {
            /* Counted amount. */
            uint32 amount = 1;

            /* Type of values counted. */
            Value.Type type = 2;

            /* Numeric type of values counted, if type is numeric. */
            optional Value.Numeric.Type numeric_value_type = 3;
        }
    }

    message Request {
        /* Pick the organization to use (/impersonate). If unset, your default organization is used. */
        optional string organization = 1;

        /* Select the values to aggregate. */
        ValueSelection selection = 2;

        /* Aggregation operation, e.g. min, max, count, sum or percentiles. */
        repeated Aggregation aggregation = 3;

        /* Time window to aggregate values, e.g. minimum per hour, maximum per day, average per week, etc. */
        optional TimeWindow window = 4;

        /* If true, groups the selected values by their owner (device or process point)
         * before applying the aggregation.
         * For example, if the selection includes data from both process point A and process point B,
         * requesting MAXIMUM will return two separate results:
         * the maximum for process point A and the maximum for process point B.
         * If false, all data is aggregated into a single value (per aggregation).
         */
        optional bool group_by_owner = 5;
    }

    message Response {
        /* The aggregated values, for each operation and window result. */
        repeated AggregatedValues results = 1;

        /* The original request, corrected and filled in with any defaults. */
        Request request = 2;
    }
}

/* Latest values for a (set of) modem(s), filtering by field and time. */
message LatestValues {
    message Request {
        /* Pick the organization to use (/impersonate). If unset, your default organization is used. */
        optional string organization = 1;
        ValueSelection selection = 2;
        optional Pagination pagination = 3;
    }

    message Response {
        repeated ValueContext values = 1;
        Pagination.Result pagination = 2;
        Request request = 3;
    }
}
